version: 2.1

jobs: 
  configure_Infrastructure:
    docker: 
      - image: python:3.7-alpine3.11
    steps: 
      - checkout
      - add_ssh_keys:
          fingerprints: ["aa:f6:6b:a1:0a:11:58:eb:54:2f:c5:20:9b:86:34:de"]
      - run:
          name: Install dependicies
          command: |
            apk add --update ansible 
      - run:
          name: configure server
          command: |
            ansible-playbook -i inventory.txt playbook.yml

workflows:
  my_workflow:
    jobs: 
      - configure_Infrastructure
        

